spring.application.name=test-spring-peliculas
spring.datasource.url=jdbc:mariadb://localhost:3306/blas-db
spring.datasource.username=blas
spring.datasource.password=blas
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# Nos permite mostrar el SQL que se lanza en el log
#spring.jpa.show-sql=true
# Nos permite especificar un dialecto SQL segun la BBDD que usemos
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Nos permite crear la BBDD si no existe
# spring.jpa.hibernate.ddl-auto=create